### ISSUE TITLE
Convert 8.x build process to composer

### ISSUE THREAD

**Issue by emarchak** [myplanetdigital/drupal-skeletor#26]
We should be looking forward to changing the build process to composer.

**Comment by gapple** [comment]
This looks worth evaluating: https://github.com/acquia/bolt

**Comment by emarchak** [comment]
It looks like Bolt scaffolds the code for the full acquia environment. I wonder if we can borrow some of it's patterns during the build process.

**Comment by emarchak** [comment]
The work is being handled in #29
